### ISSUE TITLE
Implement move_exchange!

### ISSUE THREAD

**Issue by remi-garcia** [remi-garcia/RoadefRenaultBrazil#22]
Implement `move_exchange!()` in `functions.jl`

**Comment by Jonathan-Fontaine44** [comment]
I think we should implement a `move_exchange()` that return a solution instead of changing the current solution, because we use it a lot in local search that way.

**Comment by remi-garcia** [comment]
We shouldn't make the move in the local search but only evaluate its consequences on the cost. That's why we added `cost_move_exchange()`
