### ISSUE TITLE
ArgumentError - parsing

### ISSUE THREAD

**Issue by k-fretaud** [remi-garcia/RoadefRenaultBrazil#30]
You can reproduce it with the branch _kf/tests_
`https://github.com/remi-garcia/momh-roadef2005/tree/kf/tests`
This branch was made for testing (parser and/or greedy)

```
julia> main()
Instance A/022_3_4_EP_RAF_ENP
loaded..
initial solution created..

Instance A/022_3_4_RAF_EP_ENP
loaded..
initial solution created..

Instance A/024_38_3_EP_ENP_RAF
ERROR: ArgumentError: cannot convert a DataFrame containing missing values to Matrix{Bool} (found for column HPRC1)
[...]
caused by [exception 1]
MethodError: Cannot `convert` an object of type Missing to an object of type Bool
Closest candidates are:
  convert(::Type{T<:Number}, ::T<:Number) where T<:Number at number.jl:6
  convert(::Type{T<:Number}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T<:Integer}, ::Ptr) where T<:Integer at pointer.jl:23
  ...
[...]
```

Same error for instance `A/064_38_2_RAF_EP_ENP_ch1`

**Comment by k-fretaud** [comment]
For `nom_fichier= "039_38_4_EP_RAF_ch1"` and `type_fichier = "A"`

```
Instance A/039_38_4_EP_RAF_ch1
ERROR: MethodError: no method matching occursin(::String, ::Missing)
Closest candidates are:
  occursin(::AbstractString, ::CategoricalString) at deprecated.jl:65
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:452
Stacktrace:
```

Same thing for instance of type `A` named`039_38_4_RAF_EP_ch1`

**Comment by k-fretaud** [comment]
No errors on sets `B` and `X` 
Failed instances for set `A` are:

- `A/064_38_2_RAF_EP_ENP_ch1` and `A/024_38_3_EP_ENP_RAF` (first error)
- `A/039_38_4_EP_RAF_ch1` and `A/039_38_4_RAF_EP_ch1` (second error)

First error: ???
Second error: instances have only two objectives

**Comment by remi-garcia** [comment]
`064_38_2_RAF_EP_ENP_ch1`, `024_38_3_EP_ENP_RAF` have an empty line at the end of `vehicles.txt`.
